const {test}=require('node:test');
const assert=require('node:assert/strict');
const {create}=require('./collaboration.js');
function fixture(){const calls=[];let fail=false;const api={get:async p=>{calls.push(p);return [{user_id:1,role:'OWNER'},{user_id:2,role:'VIEWER'}];},post:async(p,b)=>{calls.push([p,b]);if(fail)throw Error('offline');return p.endsWith('/accept')?7:{id:9,token:'a'.repeat(43)};},delete:async p=>{calls.push(p);if(fail)throw Error('offline');},put:async(p,b)=>calls.push([p,b])};return {model:create(api),calls,fail:()=>fail=true};}
test('changing trip or signing out clears the secret and expanded panel',async()=>{const {model}=fixture();await model.load(7);model.toggle();await model.invite('2','VIEWER');await model.load(7);assert.ok(model.issued);await model.load(8);assert.equal(model.issued,null);assert.equal(model.opened,false);await model.invite('2','VIEWER');model.reset();assert.equal(model.issued,null);assert.equal(model.role(1),undefined);});
test('invalid recipient IDs never reach server',async()=>{const {model,calls}=fixture();for(const id of ['0','-1','2.5','1e3','9007199254740993'])await assert.rejects(model.invite(id,'VIEWER'));assert.equal(calls.length,0);});
test('accept trims token, sends it in POST body, and retains server trip ID',async()=>{const {model,calls}=fixture();assert.equal(await model.accept(' '+ 'a'.repeat(43)+' '),7);assert.deepEqual(calls[0],['/api/v1/trips/invitations/accept',{token:'a'.repeat(43)}]);await assert.rejects(model.accept('bad'));assert.equal(calls.length,1);});
test('failed revoke keeps invitation available for retry',async()=>{const f=fixture();await f.model.load(7);await f.model.invite('2','VIEWER');f.fail();await assert.rejects(f.model.revoke());assert.equal(f.model.issued.id,9);});
test('role and removal mutations refresh authoritative members',async()=>{const {model,calls}=fixture();await model.load(7);assert.equal(model.role('1'),'OWNER');await model.change(2,'EDITOR');await model.remove(2);assert.deepEqual(calls.slice(1),[['/api/v1/trips/7/members/2',{role:'EDITOR'}],'/api/v1/trips/7/members','/api/v1/trips/7/members/2','/api/v1/trips/7/members']);});
test('history uses last ID cursor and revoke works without in-memory token',async()=>{
 const calls=[];const api={get:async p=>{calls.push(p);if(p.endsWith('/members'))return [];return p.endsWith('before=0')?Array.from({length:50},(_,i)=>({id:100-i})): [{id:50}];},delete:async p=>calls.push(p)};
 const model=create(api);await model.load(7);await model.history();assert.equal(model.more,true);await model.history(true);assert.equal(model.invitations.length,51);assert.equal(model.more,false);assert.equal(calls.at(-1),'/api/v1/trips/7/invitations?before=51');await model.revoke(100);assert.equal(calls.at(-1),'/api/v1/trips/7/invitations/100');await model.load(8);assert.equal(model.invitations.length,0);
});
