/* Server-backed product UI. The old local prototype is retained in separate files only. */
(() => {
  const api=window.ledgerApi, main=$('#primary');
  const names={bills:'明细',statistics:'统计',members:'成员',requests:'审批',settlement:'结算',settings:'设置'};
  const types={SHARED_EXPENSE:'共享支出',PERSONAL_EXPENSE:'个人支出',PERSONAL_INCOME:'个人收入',PERSONAL_CARRY:'临时成员代付'};
  const statuses={RUNNING:'处理中',AUTO_CONFIRMED:'已直接确认',REJECT:'已拒绝',PENDING:'待处理',PENDING_CONFIRM:'待确认',CONFIRMED:'已确认',APPROVED:'已通过',REJECTED:'已拒绝',CANCELLED:'已撤回',REVOKED:'已撤回',ACCEPTED:'已接受',EXPIRED:'已过期',ACTIVE:'使用中',DISABLED:'已停用',SUCCESS:'已完成',COMPLETED:'已完成',PROCESSING:'处理中',FAILED:'失败',OWNER:'所有者',ADMIN:'管理员',MEMBER:'成员'};
  let preserveView=false;
  let user=null, books=[], trips=[], book=null, trip=null, categories=[], bills={list:[],total:0}, overview={}, section='bills', panel={}, page=1, busy=false, error='', create=false, historyOnly=false, editor=null, uploads=[], route=null, routeError='', proposalDraft=null;
  const label=x=>statuses[x]||x||'', e=esc, currency=n=>'¥'+money(Number(n||0)), bp=()=>`/api/v1/books/${book.bookId}`;
  const button=(text,action,id='',extra='')=>`<button data-cmd="${action}" data-id="${e(id)}" ${extra}>${text}</button>`;
  const input=(title,name,value='',type='text',extra='')=>`<label>${title}<input name="${name}" type="${type}" value="${e(value)}" ${extra}></label>`;
  const select=(title,name,options,value='')=>`<label>${title}<select name="${name}">${options.map(([v,t])=>`<option value="${e(v)}" ${String(v)===String(value)?'selected':''}>${e(t)}</option>`).join('')}</select></label>`;
  const empty=text=>`<p class="ledger-empty">${e(text)}</p>`;
  const row=(title,subtitle,actions='')=>`<div class="management-row"><span><strong>${e(title)}</strong><small>${e(subtitle)}</small></span><div class="row-actions">${actions}</div></div>`;
  const form=(name,body,submit='保存')=>`<form data-form="${name}" class="connected-form">${body}<p class="form-error" role="alert"></p><button class="primary-button" type="submit">${submit}</button></form>`;
  const activeMembers=()=>book?.members.filter(x=>x.memberStatus==='ACTIVE')||[];
  const memberOptions=()=>activeMembers().map(x=>[x.memberId,x.nickname]);
  const tempOptions=()=>book?.tempParticipants.filter(x=>x.status==='ACTIVE').map(x=>[x.tempParticipantId,x.nickname])||[];
  function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(x=>x.close());}
  function popup(title,html){$('#live-title').textContent=title;$('#live-body').innerHTML=html;$('#live-dialog').showModal();}
  async function run(work,success){if(busy)return;busy=true;error='';document.body.classList.add('request-pending');try{await work();if(success)toast(success);}catch(ex){error=ex.name==='TimeoutError'?'请求超时，请刷新确认结果后再操作':ex.message;const target=$('dialog[open] .form-error');if(target)target.textContent=error;else {const inline=$('#primary .form-error');if(inline){inline.textContent=error;preserveView=true;}}toast(error);}finally{busy=false;document.body.classList.remove('request-pending');if(!$('dialog[open]')&&!document.querySelector('[data-form=search-member] #candidate-results')&&!preserveView)render();preserveView=false;}}
  async function loadLists(){[books,trips]=await Promise.all([api.get('/api/v1/books/my'),api.get('/api/v1/trips')]);}
  async function loadBook(id){book=await api.get(`/api/v1/books/${id}`);await loadLedger();}
  async function loadLedger(){const result=await Promise.all([api.get(bp()+'/categories'),api.get(bp()+`/bills?pageNo=${page}&pageSize=20`),api.get(bp()+'/statistics/overview')]);[categories,bills,overview]=result;await loadPanel();}
  async function loadPanel(){panel={};const paths={statistics:['statistics/category-consumption','statistics/member-relations','statistics/attached-temp-details'],members:['temp-participants'],requests:['bill-requests/my','bill-requests/pending-approve'],settlement:['settlements','payment-confirms/pending-receive','payment-confirms/pending-pay','payment-confirms/history','temp-recoveries'],settings:['exports']}[section]||[];const result=await Promise.all(paths.map(path=>api.get(bp()+'/'+path)));paths.forEach((path,i)=>panel[path]=result[i]);}
  async function refresh(){if(view==='ledger'&&book)await loadBook(book.bookId);else if(view==='itinerary'&&trip)await loadTrip(trip.id);else await loadLists();}
  function syncTrip(){state.trip={id:trip.id,name:trip.name,start:trip.startDate,end:trip.endDate,destination:trip.destination};state.prefs={people:trip.people,budget:trip.budgetCent/100,pace:trip.pace,style:trip.style,stay:trip.stay};const count=Math.round((Date.parse(trip.endDate)-Date.parse(trip.startDate))/86400000)+1;state.days=Array.from({length:count},(_,i)=>trip.activities.filter(a=>a.day===i).sort((a,b)=>a.time.localeCompare(b.time)));day=Math.min(day,count-1);}
  async function loadTrip(id){trip=await api.get('/api/v1/trips/'+id);syncTrip();route=null;routeError='';}
  function collectionHtml(){const isTrip=view==='itinerary', entries=isTrip?trips.filter(x=>x.archived===historyOnly):books;return `<div class="collection-toolbar"><div class="collection-tabs">${button(isTrip?'已有行程':'已有账本','current')}${isTrip?button('历史','history'):button('邀请消息','inbox')}</div>${button('＋ 新建','create','','class="primary-button"')}</div>${create?creationHtml():''}<div class="collection-list">${entries.map((x,i)=>`<article class="collection-row"><div class="collection-index">${String(i+1).padStart(2,'0')}</div><div class="collection-info"><h2>${e(x.name)}</h2><p>${isTrip?`${e(x.destination)} · ${e(x.startDate)} 至 ${e(x.endDate)}`:x.bookType==='SHARED'?'共享账本':'个人账本'}</p><span>${isTrip&&x.bookId?'已关联账本':isTrip?'独立行程':e(x.description||'')}</span></div>${button('进入 ↗',isTrip?'open-trip':'open-book',isTrip?x.id:x.bookId)}</article>`).join('')||empty('暂无记录，点击新建开始。')}</div>`;}
  function creationHtml(){return form(view==='itinerary'?'create-trip':'create-book',input('名称','name','','text','required maxlength="50"')+(view==='itinerary'?input('目的地','destination','','text','required maxlength="50"')+`<div class="form-grid">${input('出发日期','startDate','','date','required')}${input('结束日期','endDate','','date','required')}</div>`+input('人数','people',2,'number','min="1" max="30" required')+input('总预算 · 元','budget',4000,'number','min="0" max="1000000" required'):select('账本类型','bookType',[['SHARED','共享账本'],['PERSONAL','个人账本']])+input('说明','description','','text','maxlength="100"')),'创建');}
  function billList(){return `<div class="ledger-controls"><span>共 ${bills.total} 笔可见账单</span>${button('＋ 记一笔','new-bill','','class="primary-button"')}</div>${bills.list.map(b=>`<article class="ledger-bill"><button class="bill-row bill-open" data-cmd="bill-detail" data-id="${b.billId}"><span class="bill-icon">▤</span><span class="bill-info"><strong>${e(b.title)}</strong><small>${e(b.billTime?.replace('T',' '))} · ${e(b.categoryName)}</small></span><span class="bill-amount">${currency(b.billAmountCent)}<small>${e(types[b.billType])}</small></span></button></article>`).join('')||empty('还没有账单。')}<div class="row-actions">${button('上一页','page-prev','',page<=1?'disabled':'')}<span>第 ${page} 页</span>${button('下一页','page-next','',page*20>=bills.total?'disabled':'')}</div>`;}
  function statistics(){return `<h2 class="ledger-section-title">我的收支</h2>${[['垫付流水','payFlowAmountCent'],['应承担消费','accruedConsumptionAmountCent'],['待收款','receivableAmountCent'],['待付款','pendingContributionAmountCent'],['个人收入','personalIncomeAmountCent'],['已收回流水','recoveredFlowAmountCent']].map(([t,k])=>row(t,currency(overview[k]))).join('')}<h2 class="ledger-section-title">分类消费</h2>${(panel['statistics/category-consumption']||[]).map(x=>row(x.categoryName,currency(x.consumptionAmountCent))).join('')}<h2 class="ledger-section-title">成员往来</h2>${(panel['statistics/member-relations']||[]).map((x,i)=>row(x.targetMemberName,`待付 ${currency(x.iStillNeedPayTargetAmountCent)} / 待收 ${currency(x.targetStillNeedPayMeAmountCent)}`,button('往来明细','relation',i))).join('')||empty('暂无成员往来。')}<h2 class="ledger-section-title">临时成员回补</h2>${(panel['statistics/attached-temp-details']||[]).map(x=>row(x.tempParticipantNickname,`尚待回补 ${currency(x.unrecoveredAmountCent)}`,button('记录回补','recovery',x.tempParticipantId))).join('')||empty('暂无挂靠成员欠款。')}`;}
  function membersPanel(){return `${book.canInviteMember?form('search-member',select('查找方式','searchType',[['NICKNAME','昵称'],['MOBILE','手机号']])+input('搜索','keyword','','text','required maxlength="40"'),'查找成员'):''}<div id="candidate-results"></div>${activeMembers().map(m=>row(m.nickname,label(m.memberRole),m.memberId===book.currentMemberId?'':`${book.currentMemberRole==='OWNER'?button(m.memberRole==='ADMIN'?'取消管理员':'设为管理员',m.memberRole==='ADMIN'?'cancel-admin':'set-admin',m.memberId):''}${book.canRemoveMember?button('移除','remove-member',m.memberId):''}${book.canTransferOwner?button('转让所有权','transfer-owner',m.memberId):''}`)).join('')}<h2 class="ledger-section-title">临时成员</h2>${button('＋ 添加临时成员','new-temp')}${(panel['temp-participants']||[]).map(t=>row(t.nickname,`${label(t.status)} · 挂靠 ${t.attachedMember?.nickname||'未挂靠'}`,button('编辑','edit-temp',t.tempParticipantId)+(t.status==='ACTIVE'?button('删除 / 停用','delete-temp',t.tempParticipantId):button('启用','enable-temp',t.tempParticipantId)))).join('')}`;}
  function requestCards(items){return items.map(r=>`<article class="request-row"><strong>${e(r.snapshot?.title||'账单变更')} · ${r.requestType==='DELETE'?'删除':'修改'}</strong><p>${e(r.requestReason||'')} · ${e(label(r.status))}</p>${r.snapshot?`<p>${currency(r.snapshot.billAmountCent)} · ${e(r.snapshot.billTime)}</p>`:''}<div class="row-actions">${button('详情','request-detail',r.requestId)}${r.currentUserCanApprove?button('通过','approve-request',r.requestId)+button('拒绝','reject-request',r.requestId):''}${r.currentUserCanCancel?button('撤回','cancel-request',r.requestId):''}</div></article>`).join('')||empty('暂无申请。');}
  function requests(){return `<h2 class="ledger-section-title">待我审批</h2>${requestCards(panel['bill-requests/pending-approve']||[])}<h2 class="ledger-section-title">我的申请</h2>${requestCards(panel['bill-requests/my']||[])}`;}
  function paymentRows(items,receive=false){return items.map(p=>row(`${p.fromMemberName} → ${p.toMemberName}`,`${currency(p.paymentAmountCent)} · ${label(p.confirmStatus)}`,receive?button('确认收款','confirm-payment',p.paymentConfirmId)+button('拒绝','reject-payment',p.paymentConfirmId):'')).join('')||empty('暂无记录。');}
  function settlement(){return `<p class="form-note">记录线下付款及收款确认，不会发起实际转账。</p><div class="row-actions">${button('生成结算方案','settlement-form')}${button('记录已付款','payment-form')}${button('直接确认收款','receive-form')}</div><h2 class="ledger-section-title">待我确认收款</h2>${paymentRows(panel['payment-confirms/pending-receive']||[],true)}<h2 class="ledger-section-title">我已付款，等待确认</h2>${paymentRows(panel['payment-confirms/pending-pay']||[])}<h2 class="ledger-section-title">结算批次</h2>${(panel.settlements||[]).map(s=>row(`批次 ${s.settlementBatchId}`,`${s.createdAt?.replace('T',' ')} · ${s.strategyType==='MIN_TRANSFER_COUNT'?'减少转账':'直观结算'}`,button('查看方案','batch',s.settlementBatchId))).join('')||empty('暂无批次。')}<details class="ledger-details"><summary>收付款历史</summary>${paymentRows(panel['payment-confirms/history']||[])}</details><details class="ledger-details"><summary>回补记录</summary>${(panel['temp-recoveries']||[]).map(x=>row(x.tempParticipantNickname||`临时成员 ${x.tempParticipantId}`,currency(x.recoveryAmountCent))).join('')||empty('暂无回补。')}</details>`;}
  function settings(){return `${book.canEditBook?form('book-settings',input('账本名称','name',book.name,'text','required maxlength="50"')+input('说明','description',book.description||'')+input('封面','cover','','file','accept="image/png,image/jpeg,image/webp"')):''}${form('budget',input('我的预算 · 元','budget',Number(overview.currentMemberBudgetAmountCent||0)/100,'number','min="0" max="1000000" step="0.01" required'),'保存预算')}<details class="ledger-details"><summary>分类管理</summary>${categories.map(c=>row(c.name,`${c.categoryType==='INCOME'?'收入':'支出'} · ${label(c.status)}`,button('修改','edit-category',c.categoryId)+button('停用','disable-category',c.categoryId))).join('')}${button('添加分类','new-category')}</details><details class="ledger-details"><summary>行程关联</summary>${trips.filter(t=>t.bookId===book.bookId).map(t=>row(t.name,t.destination,button('查看行程','open-trip',t.id))).join('')||empty('独立账本。可在行程设置中关联。')}</details><details class="ledger-details"><summary>导出记录</summary>${exportRows(panel.exports||[])}${button('刷新状态','refresh')}</details><div class="row-actions">${book.canQuitBook?button('退出账本','quit'):''}${book.canDeleteBook?button('删除账本','delete-book'):''}</div>`;}
  function exportRows(items){return items.map(x=>row(x.exportType==='PERSONAL_DETAIL'?'个人明细':'账本汇总',`${label(x.exportStatus)} · ${x.createdAt?.replace('T',' ')}${x.errorMessage?' · '+x.errorMessage:''}`,x.exportContentJson?button('预览结果','export-record',x.exportRecordId):'')).join('')||empty('暂无导出记录。');}
  function ledger(){const pct=Number(overview.budgetUsagePercent||0);return `<div class="budget-strip"><div class="budget-label"><span>我的应承担消费</span><span>${pct.toFixed(1)}% 预算使用</span></div><div class="budget-numbers"><strong>${currency(overview.accruedConsumptionAmountCent)}</strong><span>/ 我的预算 ${currency(overview.currentMemberBudgetAmountCent)}</span></div><div class="progress-track"><i style="width:${Math.min(100,pct)}%"></i></div></div><nav class="ledger-tabs" aria-label="账本功能">${Object.entries(names).map(([k,v])=>button(v,'section',k,`class="${section===k?'active':''}" aria-current="${section===k?'page':'false'}"`)).join('')}</nav>${({bills:billList,statistics,members:membersPanel,requests,settlement,settings})[section]()}`;}
  function paper(){if(view==='ledger'&&book)return `<div class="paper-brand">SHARED LEDGER</div><div class="paper-title">${e(book.name)}</div><p class="paper-meta">当前可见明细 · 第 ${page} 页</p>${bills.list.map(b=>`<div class="paper-row"><span>${e(b.billTime?.slice(5,10))}</span><div>${e(b.title)}<small>${currency(b.billAmountCent)} · ${e(b.categoryName)}</small></div>`).join('')}<p class="paper-meta">完整导出由服务器生成，按当前成员权限裁剪。</p>`;if(!trip)return '';return `<div class="paper-brand">ITINERARY</div><div class="paper-title">${e(trip.name)}</div>${state.days.map((items,i)=>`<section class="paper-day"><b>${tripDayLabel(i)} · 第 ${i+1} 天</b>${items.map(a=>`<div class="paper-row"><span>${e(a.time)}</span><div>${e(a.title)}<small>${duration(a.duration)} · ${e(a.note)}</small></div></div>`).join('')}</section>`).join('')}`;}
  render=function(){$('#primary').setAttribute('aria-label',view==='ledger'?'账本内容':'行程内容');$('.export-stage').setAttribute('aria-label',view==='ledger'?'账本导出预览':'行程导出预览');$('.preview-paper').setAttribute('aria-label',view==='ledger'?'展开账本导出预览':'展开行程导出预览');$('#account-button').hidden=!user;$('#account-button').textContent=user?.nickname||'';const detail=view==='ledger'?!!book:view==='itinerary'?!!trip:false;document.body.classList.toggle('collection-screen',!detail);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('.breadcrumb').innerHTML=detail?button(view==='ledger'?'‹ 全部账本':'‹ 全部行程','back'):`<strong>${view==='ledger'?'Ledgers':view==='itinerary'?'Trips':'Gallery'}</strong>`;$('#page-kicker').textContent=view.toUpperCase();$('#page-title').textContent=view==='ledger'?(book?.name||'我的账本'):view==='itinerary'?(trip?.name||'我的行程'):'Gallery';$('#page-subtitle').textContent=detail?(view==='ledger'?`${activeMembers().length} 位成员 · ${label(book.currentMemberRole)}`:`${trip.people} 人 · ${trip.startDate} 至 ${trip.endDate}`):'';$('.context-panel').hidden=!detail;$('.top-actions').hidden=!detail;$('.avatars').hidden=true;$('.side-trip').hidden=true;$('.trip-stamp').hidden=!trip||view!=='itinerary';if(trip){$('.trip-stamp').innerHTML=`<span>${e(trip.destination)}</span><b>${trip.startDate.slice(8)} – ${trip.endDate.slice(8)}</b><small>${trip.startDate.slice(0,7)}</small>`;}
    $('.agent-entry').hidden=!detail;$('.agent-entry span').textContent=view==='ledger'?'帮我算账':'行程助手';$('.companion-head strong').textContent=view==='ledger'?'帮我算账':'行程助手';$('.tiny-tag').textContent=view==='ledger'?'':'轻量规划';$('.wide-link').innerHTML=view==='ledger'?'查看往来与结算 ↗':'规划偏好 ↗';$('.export-heading h2').textContent=view==='ledger'?'账本导出':'行程单';$('.export-heading p').textContent=view==='ledger'?'完整明细 · 服务端生成':'行程记录 · PDF / 打印';$('.top-actions .quiet').textContent=view==='ledger'?'↗ 导出账本':'↗ 导出行程';$('#paper-preview').innerHTML=paper();$('.prototype-note').innerHTML=user?`${e(user.nickname)}<br>${button('切换账户','logout')}`:'尚未登录';$('footer span').textContent='';$('[data-action="reset"]').hidden=true;
    const quick=$('#quick-add');quick.hidden=!user||view==='media'||(view==='itinerary'&&trip?.archived);quick.setAttribute('aria-label',view==='ledger'?(book?'记一笔':'新建账本'):(trip?'添加行程安排':'新建行程'));if(!user){main.innerHTML=loginHtml();return;}main.innerHTML=(error?`<p class="live-error" role="alert">${e(error)} ${button('重试','refresh')}</p>`:'')+(view==='media'?`<p class="section-description">账单凭据请从对应账单查看、上传；仅向有权限的成员开放。</p><section class="watermark-info"><h2>水印处理</h2><p>等待算法接入。旅行相册上传与分享尚未开放。</p></section>`:detail?(view==='ledger'?ledger():`${button('日期与关联','trip-settings')} ${trip.archived?'<p class="form-note">已归档，恢复后可编辑。</p>':''}${itineraryHtml()}`):collectionHtml());};
  function loginHtml(){return `<section class="collection-form"><h2>登录账本</h2><p class="form-note">本地开发可选择已有测试账户。正式环境使用微信登录。</p>${form('login',input('微信登录 code / 本地测试 code','code','','text','required autocomplete="off"'),'登录')}${button('选择本地测试账户','mock-users')}<div id="mock-users"></div></section>`;}
  $('.topbar').insertAdjacentHTML('beforeend','<button id="account-button" data-cmd="account" class="quiet" hidden></button>');
  document.body.insertAdjacentHTML('beforeend','<button id="quick-add" class="quick-add" data-cmd="quick-add" aria-label="新建" hidden>＋</button>');
  const stamp=document.createElement('button');stamp.className='trip-stamp';stamp.type='button';stamp.dataset.cmd='trip-settings';$('.trip-stamp').replaceWith(stamp);
  document.body.insertAdjacentHTML('beforeend','<dialog id="live-dialog" aria-labelledby="live-title"><header class="dialog-head"><h2 id="live-title"></h2><button class="icon-button" data-close="live-dialog" aria-label="关闭">×</button></header><div id="live-body"></div></dialog>');
  function billForm(b=null){editor=b;uploads=[...(b?.attachmentUrls||[])];const bt=b?.billType|| (book.shared?'SHARED_EXPENSE':'PERSONAL_EXPENSE');popup(b?'修改账单':'记一笔',form('bill',select('类型','billType',Object.entries(types),bt)+input('消费名称','title',b?.title||'','text','required maxlength="50"')+`<div class="form-grid">${input('金额 · 元','amount',b?b.billAmountCent/100:'','number','required min="0.01" step="0.01" max="1000000"')}${input('日期与时间','billTime',b?.billTime?.slice(0,16)||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),'datetime-local','required')}${select('付款人','payerMemberId',memberOptions(),b?.payer?.memberId||book.currentMemberId)}${select('记录人','recorderMemberId',memberOptions(),b?.recorder?.memberId||book.currentMemberId)}${select('分类','categoryId',categories.filter(c=>c.status==='ACTIVE').map(c=>[c.categoryId,`${c.name} (${c.categoryType==='INCOME'?'收入':'支出'})`]),b?.categoryId)}${select('代付的临时成员','tempParticipantId',[['','不适用'],...tempOptions()],b?.carryTargetTempParticipant?.tempParticipantId)}</div>`+select('共享分摊方式','shareMethod',[['AVERAGE','均分'],['FIXED_AMOUNT','指定金额'],['RATIO','按比例']],b?'FIXED_AMOUNT':'AVERAGE')+`<fieldset class="split-field"><legend>共享账单参与人（指定金额填元，比例填权重）</legend>${[...activeMembers().map(m=>({type:'MEMBER',id:m.memberId,name:m.nickname})),...book.tempParticipants.filter(t=>t.status==='ACTIVE').map(t=>({type:'TEMP_PARTICIPANT',id:t.tempParticipantId,name:t.nickname+' · 临时'}))].map(p=>{const part=b?.participants?.find(x=>x.participantType===p.type&&x.participantRefId===p.id);return `<label class="share-entry"><input type="checkbox" name="participant" value="${p.type}:${p.id}" ${part||!b?'checked':''}>${e(p.name)}<input type="number" name="share-${p.type}:${p.id}" min="0" step="0.01" value="${part?part.shareAmountCent/100:1}" aria-label="${e(p.name)}分摊值"></label>`;}).join('')}</fieldset>`+input('备注','remark',b?.remark||'','text','maxlength="200"')+(b&&!b.directEditable?input('修改原因','requestReason','','text','required maxlength="200"'):'')+input('账单凭据','receipt','','file','accept="image/png,image/jpeg,image/webp" multiple')+`<p class="form-note">${uploads.length?'已有 '+uploads.length+' 张凭据。':''}上传成功后随账单保存；审批中不会立即改变原账单。</p>`,b&&!b.directEditable?'提交修改申请':'保存账单'));updateBillFields();}
  function updateBillFields(){const f=$('[data-form="bill"]');if(!f)return;const type=f.elements.billType.value,shared=type==='SHARED_EXPENSE',income=type==='PERSONAL_INCOME';const selected=f.elements.categoryId.value;f.elements.categoryId.innerHTML=categories.filter(c=>c.status==='ACTIVE'&&c.categoryType===(income?'INCOME':'EXPENSE')).map(c=>`<option value="${c.categoryId}" ${String(c.categoryId)===selected?'selected':''}>${e(c.name)}</option>`).join('');f.elements.tempParticipantId.closest('label').hidden=type!=='PERSONAL_CARRY';f.elements.shareMethod.closest('label').hidden=!shared;f.querySelector('fieldset').hidden=!shared;f.querySelectorAll('.share-entry input[type=number]').forEach(x=>x.hidden=f.elements.shareMethod.value==='AVERAGE');}
  window.addEventListener('change',event=>{if(event.target.closest('[data-form="bill"]'))updateBillFields();},true);
  async function billDetail(id){const b=await api.get(bp()+'/bills/'+id);editor=b;popup(b.title,`<p>${currency(b.billAmountCent)} · ${e(types[b.billType])} · ${e(b.categoryName)}</p><p>${e(b.billTime)} · ${e(b.payer?.nickname)}付款</p><p>${e(b.remark)}</p>${(b.participants||[]).map(p=>row(p.nickname,`分摊 ${currency(p.shareAmountCent)} / 未结 ${currency(p.unconfirmedAmountCent)}`,p.participantType==='MEMBER'&&p.participantRefId!==b.payer?.memberId&&p.unconfirmedAmountCent>0?button('记录该成员已结清','settle-participant',p.participantRefId):'')).join('')}<div class="row-actions">${button(b.directEditable?'修改':'申请修改','edit-bill')}${button(b.directDeletable?'删除':'申请删除','delete-bill')}${button('变更历史','bill-history',id)}</div><h3>凭据</h3><div id="receipt-list">${(b.attachmentUrls||[]).map((url,i)=>button('查看凭据 '+(i+1),'receipt',i)).join('')||empty('暂无凭据。')}</div>`);}
  async function inbox(){const [received,sent]=await Promise.all([api.get('/api/v1/invitations/received'),api.get('/api/v1/invitations/sent')]);popup('邀请消息',`<h3>收到的邀请</h3>${received.map(x=>row(x.bookName,`${x.inviterNickname} · ${label(x.status)}`,x.status==='PENDING'?button('接受','accept-invite',x.invitationId)+button('拒绝','reject-invite',x.invitationId):'')).join('')||empty('暂无邀请。')}<h3>发出的邀请</h3>${sent.map(x=>row(x.inviteeNickname,`${x.bookName} · ${label(x.status)}`,x.canRevoke?button('撤回','revoke-invite',x.invitationId):'')).join('')||empty('暂无邀请。')}`);}
  function confirmAction(title,cmd,id,body='此操作会更新服务器上的记录。'){popup(title,`<p>${e(body)}</p><div class="row-actions">${button('确认','confirmed-'+cmd,id,'class="primary-button"')}<button data-close="live-dialog">取消</button></div>`);}
  async function login(code){const result=await api.post('/api/v1/auth/wechat-login',{code});if(result.needBindMobile){api.setSession({token:result.bindToken});popup('完善账户',form('bind-mobile',input('昵称','nickname','','text','required')+input('手机号（仅本地开发）','manualMobile','','tel','required pattern="1[0-9]{10}"')));return;}if(!result.token)throw new Error('该账户暂不可登录');api.setSession(result);user=await api.get('/api/v1/users/me');await loadLists();closeDialogs();}
  async function action(cmd,id){
    if(cmd==='mock-users'){const list=await api.get('/api/v1/auth/dev/mock-users');preserveView=true;$('#mock-users').innerHTML=list.map(x=>row(x.nickname,x.mobileMasked,button('登录','mock-login',x.suggestedCode))).join('')||empty('暂无测试账户，可填写新的本地 code 创建。');return;}
    if(cmd==='mock-login')return login(id);
    if(cmd==='account'){popup('当前账户',`<p>${e(user.nickname)}</p><p>${e(user.mobileMasked||'')}</p>${button('退出登录 / 切换账户','logout')}`);return;}
    if(cmd==='logout'){api.setSession(null);user=null;book=null;trip=null;closeDialogs();return;}
    if(cmd==='open-book'){view='ledger';section='bills';page=1;await loadBook(id);history.replaceState(null,'',`#ledger/${id}`);return;}
    if(cmd==='open-trip'){view='itinerary';day=0;showRoute=false;await loadTrip(id);history.replaceState(null,'',`#itinerary/${id}`);return;}
    if(cmd==='back'){book=null;trip=null;create=false;await loadLists();history.replaceState(null,'','#'+view);return;}
    if(cmd==='current'||cmd==='history'){historyOnly=cmd==='history';create=false;return;}
    if(cmd==='create'){create=!create;return;}
    if(cmd==='refresh')return refresh();
    if(cmd==='section'){section=id;await loadPanel();return;}
    if(cmd==='page-prev'||cmd==='page-next'){page+=cmd==='page-prev'?-1:1;return loadLedger();}
    if(cmd==='new-bill')return billForm();
    if(cmd==='bill-detail')return billDetail(id);
    if(cmd==='edit-bill')return billForm(editor);
    if(cmd==='delete-bill'){if(editor.directDeletable)return confirmAction('删除账单','delete-bill',editor.billId);popup('申请删除账单',form('delete-request',input('删除原因','requestReason','','text','required maxlength="200"'),'提交申请'));return;}
    if(cmd==='confirmed-delete-bill'){await api.delete(bp()+'/bills/'+id);closeDialogs();return refresh();}
    if(cmd==='bill-history'){const list=await api.get(bp()+'/bills/'+id+'/change-requests');popup('账单变更历史',requestCards(list));return;}
    if(cmd==='request-detail'){const r=await api.get(bp()+'/bill-requests/'+id);popup('申请详情',requestCards([r])+`<h3>分摊方案</h3>${(r.snapshot?.shareItems||[]).map(x=>row(x.participantName,currency(x.shareAmountCent))).join('')}<h3>审批记录</h3>${(r.approvalRecords||[]).map(x=>row(label(x.approvalAction),x.approvalComment||x.createdAt)).join('')}`);return;}
    if(['approve-request','reject-request','cancel-request'].includes(cmd)){await api.post(bp()+`/bill-requests/${id}/${cmd.split('-')[0]}`);closeDialogs();return refresh();}
    if(cmd==='receipt'){const url=await api.image(editor.attachmentUrls[Number(id)]);const img=document.createElement('img');img.className='receipt-image';img.alt='账单凭据';img.src=url;img.onload=()=>URL.revokeObjectURL(url);$('#receipt-list').replaceChildren(img);return;}
    if(cmd==='inbox')return inbox();
    if(cmd==='invite'){await api.post(bp()+'/invitations',{inviteeUserId:Number(id)});toast('已发送邀请');return;}
    if(['accept-invite','reject-invite','revoke-invite'].includes(cmd)){await api.post('/api/v1/invitations/'+id+'/'+cmd.split('-')[0]);await loadLists();return inbox();}
    if(['set-admin','cancel-admin'].includes(cmd)){await api.post(bp()+`/members/${id}/${cmd}`);return refresh();}
    if(['remove-member','transfer-owner','quit','delete-book','delete-temp'].includes(cmd))return confirmAction('确认'+({ 'remove-member':'移除成员','transfer-owner':'转让所有权',quit:'退出账本','delete-book':'删除账本','delete-temp':'删除或停用临时成员'}[cmd]),cmd,id);
    if(cmd==='confirmed-remove-member')await api.post(bp()+`/members/${id}/remove`);
    if(cmd==='confirmed-transfer-owner')await api.post(bp()+'/transfer-owner',{targetMemberId:Number(id)});
    if(cmd==='confirmed-quit'||cmd==='confirmed-delete-book'){if(cmd==='confirmed-quit')await api.post(bp()+'/quit');else await api.delete(bp());book=null;await loadLists();}
    if(cmd==='confirmed-delete-temp')await api.delete(bp()+'/temp-participants/'+id);
    if(cmd.startsWith('confirmed-')){closeDialogs();return refresh();}
    if(cmd==='enable-temp'){await api.post(bp()+`/temp-participants/${id}/enable`);return refresh();}
    if(cmd==='new-temp'||cmd==='edit-temp'){editor=cmd==='edit-temp'?panel['temp-participants'].find(x=>String(x.tempParticipantId)===id):null;popup(editor?'编辑临时成员':'添加临时成员',form('temp',input('昵称','nickname',editor?.nickname||'','text','required maxlength="30"')+(!editor?select('范围','tempType',[['GLOBAL','账本共用'],['PRIVATE','个人临时成员']]):'')+select('挂靠成员','attachedMemberId',[['','不挂靠'],...memberOptions()],editor?.attachedMember?.memberId)));return;}
    if(cmd==='new-category'||cmd==='edit-category'){editor=categories.find(c=>String(c.categoryId)===id)||null;popup(editor?'修改分类':'添加分类',form('category',input('名称','name',editor?.name||'','text','required maxlength="20"')+(!editor?select('收支类型','categoryType',[['EXPENSE','支出'],['INCOME','收入']])+select('分类范围','categorySource',[['CUSTOM_GLOBAL','账本共用'],['CUSTOM_LOCAL','个人自定义']]):'')));return;}
    if(cmd==='disable-category'){await api.post(bp()+`/categories/${id}/disable`);return refresh();}
    if(cmd==='settlement-form'){popup('生成结算方案',form('settlement',select('策略','strategyType',[['INTUITIVE_FIRST','直观结算'],['MIN_TRANSFER_COUNT','减少转账次数']]),'生成'));return;}
    if(cmd==='batch'){const batch=await api.get(bp()+'/settlements/'+id);popup('结算方案',`<p class="form-note">方案只是一份快照，付款仍需收款方确认。</p>${batch.transferList.map(t=>row(`${t.fromMemberName} → ${t.toMemberName}`,currency(t.transferAmountCent),t.fromMemberId===book.currentMemberId?button('记录付款','transfer-payment',t.transferId):'')).join('')||empty('没有需要结算的转账。')}`);panel.batch=batch;return;}
    if(cmd==='transfer-payment'){const t=panel.batch.transferList.find(t=>String(t.transferId)===id);await api.post(bp()+'/payment-confirms',{toMemberId:t.toMemberId,paymentAmountCent:t.transferAmountCent,sourceType:'SETTLEMENT_TRANSFER',sourceRefId:t.transferId});closeDialogs();return refresh();}
    if(cmd==='payment-form'||cmd==='receive-form'){popup(cmd==='payment-form'?'记录已付款':'直接确认收款',form(cmd,select(cmd==='payment-form'?'收款成员':'付款成员','memberId',memberOptions().filter(([id])=>id!==book.currentMemberId))+input('金额 · 元','amount','','number','required min="0.01" step="0.01" max="1000000"')+input('备注','remark','','text','maxlength="50"')));return;}
    if(cmd==='confirm-payment'||cmd==='reject-payment'){await api.post(bp()+`/payment-confirms/${id}/${cmd==='confirm-payment'?'confirm':'reject'}`);return refresh();}
    if(cmd==='recovery'){editor={tempParticipantId:Number(id)};popup('记录临时成员回补',form('recovery',input('回补金额 · 元','amount','','number','required min="0.01" step="0.01" max="1000000"')+input('备注','remark','','text','maxlength="50"')));return;}
    if(cmd==='settle-participant'){await api.post(bp()+`/bills/${editor.billId}/participants/${id}/settle`);await loadLedger();return billDetail(editor.billId);}
    if(cmd==='relation'){const r=panel['statistics/member-relations'][Number(id)];const both=await Promise.all(['PAYABLE','RECEIVABLE'].map(direction=>api.get(bp()+`/statistics/member-relations/details?direction=${direction}&targetType=${encodeURIComponent(r.targetParticipantType)}&targetId=${r.targetParticipantId}`)));popup('往来明细',both.map((items,i)=>`<h3>${i?'待收 / 已收':'待付 / 已付'}</h3>${items.map(b=>row(b.title,`金额 ${currency(b.amountCent)} / 未结 ${currency(b.unpaidAmountCent)}`)).join('')||empty('暂无明细。')}`).join(''));return;}
    if(cmd==='export'){if(view==='ledger'){popup('导出账本',`<div class="row-actions">${book.currentMemberRole==='OWNER'?button('账本汇总','export-book'):''}${button('我的个人明细','export-personal')}</div><p class="form-note">异步生成完整记录，仅包含当前账户有权导出的内容。</p>${button('刷新导出状态','export')}${exportRows(await api.get(bp()+'/exports'))}`);}else{$('#export-document').innerHTML=paper();$('#export-title').textContent='行程单';$('#export-dialog').showModal();}return;}
    if(cmd==='export-book'||cmd==='export-personal'){await api.post(bp()+'/exports/'+(cmd==='export-book'?'book-summary':'personal-detail'));toast('导出任务已提交，可刷新查看结果');return action('export');}
    if(cmd==='export-record'){const records=await api.get(bp()+'/exports');const r=records.find(x=>String(x.exportRecordId)===id);if(!r?.exportContentJson)throw new Error('导出仍在处理中');const data=JSON.parse(r.exportContentJson);$('#export-document').innerHTML=exportDocument(data);$('#export-title').textContent='账本导出';closeDialogs();$('#export-dialog').showModal();return;}
    if(cmd==='agent'){if(view==='ledger'){section='statistics';await loadPanel();closeDialogs();return;}return planner();}
    if(cmd==='trip-settings')return tripSettings();
    if(cmd==='trip-archive'){await saveTrip({...trip,archived:!trip.archived});closeDialogs();return;}
    if(cmd==='route'){showRoute=!showRoute;if(showRoute)await loadRoute();return;}
    if(cmd==='route-refresh')return loadRoute();
    if(cmd==='apply-plan'){await api.post(`/api/v1/trips/${trip.id}/plans/${proposalDraft.id}/apply`,{version:trip.version});await loadTrip(trip.id);closeDialogs();return;}
  }
  function exportDocument(data){const items=data.billList||[];return `<div class="paper-brand">SHARED LEDGER</div><div class="paper-title">${e(data.bookName||book.name)}</div><p class="paper-meta">${items.length} 笔可见账单 · 导出快照</p>${items.map(b=>`<div class="paper-row"><span>${e(Array.isArray(b.billTime)?b.billTime.slice(0,3).map((n,i)=>i?String(n).padStart(2,'0'):n).join('-'):String(b.billTime||'').slice(0,10))}</span><div>${e(b.title)} · ${currency(b.billAmountCent)}<small>${e(b.categoryName)} · ${e(types[b.billType])} · 我的分摊 ${currency(b.viewerOwnShareAmountCent)}</small></div></div>`).join('')}<p class="paper-meta">不包含私密凭据。记录付款不代表实际转账。</p>`;}
  const cents=window.ledgerAmounts.cents;
  async function upload(file,type,billId){const fd=new FormData();fd.set('file',file);fd.set('type',type);if(book)fd.set('bookId',book.bookId);if(billId)fd.set('billId',billId);return (await api.request('/api/v1/files/upload',{method:'POST',body:fd})).fileUrl;}
  async function submit(formEl){const f=new FormData(formEl),value=Object.fromEntries(f),kind=formEl.dataset.form||formEl.id;
    if(kind==='login')return login(value.code.trim());
    if(kind==='bind-mobile'){const result=await api.post('/api/v1/auth/bind-wechat-mobile',value);api.setSession(result);user=await api.get('/api/v1/users/me');await loadLists();closeDialogs();return;}
    if(kind==='create-book'){const result=await api.post('/api/v1/books',value);create=false;section='bills';await loadLists();history.replaceState(null,'',`#ledger/${result.bookId}`);return loadBook(result.bookId);}
    if(kind==='create-trip'){const result=await api.post('/api/v1/trips',{...value,people:Number(value.people),budgetCent:cents(value.budget),pace:'balanced',style:'classic',stay:'metro',activities:[]});create=false;await loadLists();history.replaceState(null,'',`#itinerary/${result.id}`);return loadTrip(result.id);}
    if(kind==='bill'){
      const data={billType:value.billType,title:value.title.trim(),billAmountCent:cents(value.amount),billTime:value.billTime.length===16?value.billTime+':00':value.billTime,categoryId:Number(value.categoryId),payerMemberId:Number(value.payerMemberId),recorderMemberId:Number(value.recorderMemberId),tempParticipantId:value.tempParticipantId?Number(value.tempParticipantId):null,remark:value.remark,requestReason:value.requestReason};
      if(data.billType==='SHARED_EXPENSE'){const selected=f.getAll('participant');if(!selected.length)throw new Error('请选择分摊成员');const amounts=window.ledgerAmounts.allocate(data.billAmountCent,value.shareMethod,selected.map(key=>value['share-'+key]));data.shareItems=selected.map((key,i)=>{const [participantType,id]=key.split(':');return {participantType,participantRefId:Number(id),shareMethod:value.shareMethod,shareAmountCent:amounts[i],shareRatio:value.shareMethod==='RATIO'?Number(value['share-'+key]):null};});if(value.shareMethod==='FIXED_AMOUNT'&&data.shareItems.reduce((s,x)=>s+x.shareAmountCent,0)!==data.billAmountCent)throw new Error('指定分摊金额之和必须等于账单总金额');}
      for(const file of f.getAll('receipt').filter(x=>x.size)) uploads.push(await upload(file,'billing',editor?.billId));data.attachmentUrls=uploads;
      if(editor){if(editor.directEditable)await api.put(bp()+'/bills/'+editor.billId,data);else await api.post(bp()+`/bills/${editor.billId}/modify-requests`,data);}else await api.post(bp()+'/bills/'+(data.billType==='SHARED_EXPENSE'?'shared-expense':'personal-bill'),data);
    }else if(kind==='delete-request'){await api.post(bp()+`/bills/${editor.billId}/delete-requests`,value);
    }else if(kind==='search-member'){const list=await api.get(bp()+`/invitation-candidates?searchType=${value.searchType}&keyword=${encodeURIComponent(value.keyword)}`);preserveView=true;$('#candidate-results').innerHTML=list.map(m=>row(m.nickname,m.phoneNumber||'',button(m.pendingInvitation?'已邀请':'邀请','invite',m.userId,m.pendingInvitation?'disabled':''))).join('')||empty('没有符合条件的用户。');return;
    }else if(kind==='temp'){const attachedMemberId=value.attachedMemberId?Number(value.attachedMemberId):null;if(editor){await api.put(bp()+`/temp-participants/${editor.tempParticipantId}/nickname`,{nickname:value.nickname});await api.put(bp()+`/temp-participants/${editor.tempParticipantId}/attached-member`,{attachedMemberId});}else await api.post(bp()+'/temp-participants',{nickname:value.nickname,tempType:value.tempType,attachedMemberId});
    }else if(kind==='category'){if(editor)await api.put(bp()+`/categories/${editor.categoryId}`,{name:value.name});else await api.post(bp()+'/categories',value);
    }else if(kind==='book-settings'){let coverUrl=book.coverUrl;if(value.cover?.size)coverUrl=await upload(value.cover,'cover');await api.put(bp(),{name:value.name,description:value.description,coverUrl});
    }else if(kind==='budget'){await api.put(bp()+'/statistics/budget',{budgetAmountCent:cents(value.budget)});
    }else if(kind==='settlement'){const batch=await api.post(bp()+'/settlements',value);await loadPanel();return action('batch',batch.settlementBatchId);
    }else if(kind==='payment-form'||kind==='receive-form'){await api.post(bp()+'/payment-confirms'+(kind==='receive-form'?'/direct-receive':''),{[kind==='receive-form'?'fromMemberId':'toMemberId']:Number(value.memberId),paymentAmountCent:cents(value.amount),sourceType:'MANUAL',remark:value.remark});
    }else if(kind==='recovery'){await api.post(bp()+'/temp-recoveries',{tempParticipantId:editor.tempParticipantId,recoveryAmountCent:cents(value.amount),remark:value.remark});
    }else if(kind==='trip-settings'){await saveTrip({...trip,...value,bookId:value.bookId?Number(value.bookId):null,people:Number(value.people),budgetCent:cents(value.budget)});
    }else if(kind==='activity-form'){const activities=[...trip.activities];const old=activities.find(a=>a.id===editingId);const next={...(old||{}),id:editingId||crypto.randomUUID(),day,title:value.title,time:value.time,duration:Number(value.duration),note:value.note,color:old?.color||'blue',locked:old?.locked||false,done:old?.done||false,poiId:value.poiId||null,longitude:value.longitude?Number(value.longitude):null,latitude:value.latitude?Number(value.latitude):null};await saveTrip({...trip,activities:old?activities.map(a=>a.id===old.id?next:a):[...activities,next]});
    }else if(kind==='planner'){const result=await api.post(`/api/v1/trips/${trip.id}/plans`,{...value,people:Number(value.people),budgetCent:cents(value.budget),version:trip.version});proposalDraft=result;$('#plan-result').innerHTML=`<p>${e(result.explanation)}</p>${result.activities.map(a=>row(`第 ${a.day+1} 天 ${a.time} · ${a.title}`,a.note||'')).join('')}${result.activities.length?button('采纳草案','apply-plan',result.id,'class="primary-button"'):''}`;return;
    }else if(kind==='poi-search'){const pois=await api.get(`/api/v1/trips/${trip.id}/places?keyword=${encodeURIComponent(value.keyword)}`);$('#poi-results').innerHTML=pois.map((p,i)=>row(p.name,p.address,button('选用','choose-poi',i))).join('')||empty('没有找到地点。');panel.pois=pois;return;
    }else return;
    closeDialogs();await refresh();toast('已保存');
  }
  async function saveTrip(next){trip=await api.put('/api/v1/trips/'+trip.id,next);syncTrip();route=null;await loadLists();}
  function tripSettings(){popup('行程设置',form('trip-settings',input('名称','name',trip.name,'text','required maxlength="50"')+input('目的地','destination',trip.destination,'text','required maxlength="50"')+`<div class="form-grid">${input('出发日期','startDate',trip.startDate,'date','required')}${input('结束日期','endDate',trip.endDate,'date','required')}${input('人数','people',trip.people,'number','required min="1" max="30"')}${input('总预算 · 元','budget',trip.budgetCent/100,'number','required min="0" max="1000000"')}</div>`+select('关联账本','bookId',[['','不关联'],...books.map(b=>[b.bookId,b.name])],trip.bookId))+button(trip.archived?'恢复行程':'归档行程','trip-archive'));}
  function planner(){popup('行程助手',form('planner',input('需求','message','','text','required maxlength="1000" placeholder="例如：轻松一些，想看博物馆"')+`<div class="form-grid">${input('人数','people',trip.people,'number','required min="1" max="30"')}${input('预算 · 元','budget',trip.budgetCent/100,'number','required min="0" max="1000000"')}${select('节奏','pace',[['relaxed','轻松'],['balanced','适中'],['packed','紧凑']],trip.pace)}${select('偏好','style',[['culture','文化体验'],['classic','经典必去'],['nature','自然景观']],trip.style)}${select('住宿','stay',[['metro','地铁附近'],['quiet','安静区域'],['central','市中心']],trip.stay)}</div><p class="form-note">从真实地点候选生成顺序草案，保留已锁定安排；采纳前请检查营业时间与预约。</p>`,'生成草案')+'<section id="plan-result" aria-live="polite"></section>');}
  const originalOpenActivity=openActivity;
  openActivity=function(item=null){if(trip.archived){toast('请先恢复行程');return;}originalOpenActivity(item);const f=$('#activity-form');for(const name of ['poiId','longitude','latitude'])f.elements[name].value=item?.[name]??'';$('#poi-results').innerHTML='';};
  $('#activity-form .form-note').textContent='地点坐标用于路线生成，无需当前位置。手动安排可先保存，补充地点后再生成路线。';
  $('#activity-form .form-note').insertAdjacentHTML('beforebegin',`<details><summary>地点坐标</summary>${input('地点 ID','poiId')}${input('经度','longitude','','number','step="any" min="-180" max="180"')}${input('纬度','latitude','','number','step="any" min="-90" max="90"')}</details>`);
  $('#activity-form').insertAdjacentHTML('afterend',form('poi-search',input('搜索地点','keyword','','text','required maxlength="100"'),'查询地点')+'<div id="poi-results"></div>');
  async function loadRoute(){routeError='';try{route=await api.get(`/api/v1/trips/${trip.id}/route?day=${day}&mode=walking`);}catch(ex){route=null;routeError=ex.message;}}
  routeHtml=function(){if(!route)return `<section class="route-diagram"><h3>今日路线</h3><p>${e(routeError||'路线尚未生成')}</p>${button('重新查询','route-refresh')}</section>`;const coords=route.coordinates;if(!coords?.length)return empty('这一天暂无可绘制路线。');const xs=coords.map(c=>c[0]),ys=coords.map(c=>c[1]),xmin=Math.min(...xs),ymin=Math.min(...ys),dx=Math.max(...xs)-xmin||.001,dy=Math.max(...ys)-ymin||.001;const latitudeScale=Math.cos((ymin+dy/2)*Math.PI/180);const scale=Math.min(500/(dx*latitudeScale),300/dy);const project=c=>[280+((c[0]-xmin)-dx/2)*latitudeScale*scale,180-((c[1]-ymin)-dy/2)*scale];const path=coords.map((c,i)=>(i?'L':'M')+project(c).join(',')).join(' ');return `<section class="route-diagram"><header><strong>今日路线 · ${e(route.provider)}</strong>${button('播放 / 暂停','play-route')}</header><svg viewBox="0 0 560 360" role="img" aria-label="当天步行路线"><path id="live-route-path" d="${path}" fill="none" stroke="currentColor" stroke-width="3"/><circle r="6" fill="#bc9552"><animateMotion dur="12s" repeatCount="indefinite"><mpath href="#live-route-path"/></animateMotion></circle>${route.stops.map((s,i)=>{const [x,y]=project([s.longitude,s.latitude]);return `<g><circle cx="${x}" cy="${y}" r="11" fill="#f5f4f0" stroke="currentColor"/><text x="${x}" y="${y+4}" font-size="12" text-anchor="middle">${i+1}</text></g>`;}).join('')}</svg><p>${(route.distanceMeters/1000).toFixed(1)} km · 预计 ${Math.round(route.durationSeconds/60)} 分钟步行</p><ol>${route.stops.map(s=>`<li>${e(s.title)}</li>`).join('')}</ol><p class="form-note">道路几何来自地图服务。此视图未叠加地图底图；营业与预约信息需另行确认。</p></section>`;};
  window.addEventListener('click',event=>{const b=event.target.closest('button,a.brand');if(!b)return;if(b.type==='submit'&&b.form)return;event.preventDefault();event.stopImmediatePropagation();if(b.dataset.close){$(`#${b.dataset.close}`).close();render();return;}if(busy)return;run(async()=>{
    if(b.dataset.view||b.matches('a.brand')){view=b.dataset.view||'itinerary';book=null;trip=null;create=false;error='';history.replaceState(null,'','#'+view);if(user)await loadLists();return;}
    if(b.dataset.cmd==='choose-poi'){const p=panel.pois[Number(b.dataset.id)],f=$('#activity-form');f.elements.title.value=p.name;f.elements.poiId.value=p.id;f.elements.longitude.value=p.longitude;f.elements.latitude.value=p.latitude;$('#poi-results').innerHTML=empty('已选用 '+p.name);return;}
    if(b.dataset.cmd==='play-route'){const svg=$('.route-diagram svg');if(svg.animationsPaused())svg.unpauseAnimations();else svg.pauseAnimations();return;}
    if(b.dataset.cmd==='quick-add'){if(view==='itinerary'&&trip)return openActivity();if(view==='ledger'&&book)return billForm();create=true;return;}
    if(b.dataset.cmd)return action(b.dataset.cmd,b.dataset.id);
    if(b.dataset.day!==undefined){day=Number(b.dataset.day);expanded=null;if(showRoute)await loadRoute();return;}
    if(b.dataset.expand){expanded=expanded===b.dataset.expand?null:b.dataset.expand;return;}
    for(const key of ['complete','lock','edit','delete','bill'])if(b.dataset[key]){const a=trip.activities.find(x=>x.id===b.dataset[key]);if(key==='edit')return openActivity(a);if(key==='bill'){if(!trip.bookId)throw new Error('请先在行程设置中关联账本');await loadBook(trip.bookId);billForm();$('#live-body [name=title]').value=a.title;return;}if(trip.archived)throw new Error('请先恢复行程');const activities=structuredClone(trip.activities);const item=activities.find(x=>x.id===a.id);if(key==='complete')item.done=!item.done;if(key==='lock')item.locked=!item.locked;if(key==='delete'&&(a.locked||a.done))throw new Error('请先解锁或取消打卡');return saveTrip({...trip,activities:key==='delete'?activities.filter(x=>x.id!==a.id):activities});}
    if(b.dataset.action==='add-activity')return openActivity();if(b.dataset.action==='print'){window.print();return;}if(b.dataset.action)return action(b.dataset.action);
  });},true);
  window.addEventListener('submit',event=>{event.preventDefault();event.stopImmediatePropagation();run(()=>submit(event.target));},true);
  // Retire the old prototype's local persistence paths; all mutations above await the server.
  save=()=>{throw new Error('请通过服务端保存变更');};
  window.addEventListener('hashchange',()=>run(readRoute));
  async function readRoute(){const [kind,id]=location.hash.slice(1).split('/');view=['ledger','itinerary','media'].includes(kind)?kind:'itinerary';book=null;trip=null;if(user&&id&&/^\d+$/.test(id)){if(view==='ledger')await loadBook(id);if(view==='itinerary')await loadTrip(id);}}
  render();run(async()=>{if(api.session?.token){user=await api.get('/api/v1/users/me');await loadLists();await readRoute();}});
})();
