const {test}=require('node:test');const assert=require('node:assert/strict');const {create}=require('./trip-push.js');
function fixture(){const sockets=[],timers=new Map();let seq=0,notices=0;class Socket{constructor(url){this.url=url;this.sent=[];sockets.push(this);}send(s){this.sent.push(JSON.parse(s));}close(){this.closed=true;this.onclose?.();}}
const model=create({Socket,url:'ws://local/ws/trips',notify:()=>notices++,schedule:(fn,ms)=>{timers.set(++seq,{fn,ms});return seq;},cancel:id=>timers.delete(id)});return {model,sockets,timers,get notices(){return notices;}};}
test('auth stays in first message and hints request catch-up',()=>{const f=fixture();f.model.start(7,'secret');const ws=f.sockets[0];assert.equal(ws.url,'ws://local/ws/trips');ws.onopen();assert.deepEqual(ws.sent,[{token:'secret',tripId:7}]);ws.onmessage({data:'{"type":"ready"}'});ws.onmessage({data:'{"type":"changed"}'});assert.equal(f.notices,2);f.model.start(7,'secret');assert.equal(f.sockets.length,1);});
test('trip switch ignores old hints and closes old socket',()=>{const f=fixture();f.model.start(7,'a');const old=f.sockets[0];f.model.start(8,'a');old.onmessage({data:'{"type":"changed"}'});assert.equal(f.notices,0);assert.equal(old.closed,true);f.model.stop();assert.equal(f.timers.size,0);});
test('disconnect reconnects with bounded backoff; logout cancels retry',()=>{const f=fixture();f.model.start(7,'a');f.sockets[0].onclose();const retry=[...f.timers.values()][0];assert.ok(retry.ms>=1000&&retry.ms<1500);f.model.stop();assert.equal(f.timers.size,0);retry.fn();assert.equal(f.sockets.length,1);});
test('missing heartbeat closes stale connection for recovery',()=>{const f=fixture();f.model.start(7,'a');const ws=f.sockets[0];ws.onopen();const expiry=[...f.timers.values()].find(x=>x.ms===45000);expiry.fn();assert.equal(ws.closed,true);});

test('unavailable websocket transport leaves HTTP fallback running',()=>{let delay;const m=create({Socket:class {constructor(){throw Error('unsupported');}},url:'ws://local',notify:()=>{},schedule:(fn,ms)=>{delay=ms;return 1;},cancel:()=>{}});assert.doesNotThrow(()=>m.start(7,'a'));assert.equal(delay,30000);m.stop();});
