package com.spvermicelli.tripledger.shared.domain.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum OperationType implements BaseDbEnum {
    CREATE_BOOK("CREATE_BOOK"),
    UPDATE_BOOK("UPDATE_BOOK"),
    ADD_MEMBER("ADD_MEMBER"),
    REMOVE_MEMBER("REMOVE_MEMBER"),
    REJOIN_MEMBER("REJOIN_MEMBER"),
    SET_ADMIN("SET_ADMIN"),
    CANCEL_ADMIN("CANCEL_ADMIN"),
    CREATE_BILL("CREATE_BILL"),
    UPDATE_BILL("UPDATE_BILL"),
    DELETE_BILL("DELETE_BILL"),
    CREATE_TEMP_PARTICIPANT("CREATE_TEMP_PARTICIPANT"),
    UPDATE_TEMP_PARTICIPANT_NICKNAME("UPDATE_TEMP_PARTICIPANT_NICKNAME"),
    CHANGE_TEMP_PARTICIPANT_ATTACHED_MEMBER("CHANGE_TEMP_PARTICIPANT_ATTACHED_MEMBER"),
    CREATE_CHANGE_REQUEST("CREATE_CHANGE_REQUEST"),
    CANCEL_CHANGE_REQUEST("CANCEL_CHANGE_REQUEST"),
    APPROVE_CHANGE_REQUEST("APPROVE_CHANGE_REQUEST"),
    REJECT_CHANGE_REQUEST("REJECT_CHANGE_REQUEST"),
    CREATE_SETTLEMENT("CREATE_SETTLEMENT"),
    INITIATE_PAYMENT_CONFIRM("INITIATE_PAYMENT_CONFIRM"),
    REJECT_PAYMENT("REJECT_PAYMENT"),
    DIRECT_RECEIVE_PAYMENT("DIRECT_RECEIVE_PAYMENT"),
    CONFIRM_PAYMENT("CONFIRM_PAYMENT"),
    AUTO_CONFIRM_PAYMENT("AUTO_CONFIRM_PAYMENT"),
    CONFIRM_TEMP_RECOVERY("CONFIRM_TEMP_RECOVERY"),
    EXPORT_DATA("EXPORT_DATA");

    @EnumValue
    @JsonValue
    private final String code;
}
